name: plant_care
description: "A mobile application to track and manage plant care routines."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.3      # Local storage for web and mobile
  image_picker: ^1.1.2            # For uploading/selecting images
  sqflite: ^2.3.3                 # Local database for storing data
  path_provider: ^2.1.3           # For accessing device file paths
  carousel_slider: ^5.1.1
  path: ^1.8.3                    # For file paths if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/greenbush.jpg
    - assets/images/plant1.jpg
    - assets/images/plant2.jpg
    - assets/images/plant3.jpg
    - assets/images/plant4.jpg